name = 'aiken-lang/staking'
version = '0.0.0'
license = 'Apache-2.0'
description = 'Noncustodial staking for NFT'

[repository]
user = 'aiken-lang'
project = 'staking'
platform = 'github'

[[dependencies]]
name = "aiken-lang/stdlib"
version = "main"
source = "github"